services:
  vendor-service:
    build:
      context: ./Vendors
      dockerfile: Dockerfile
    container_name: vendor-service-martinez
    working_dir: /app
    volumes:
      - ./Vendors:/app
      - ./_shared:/app/_shared
      - /app/node_modules
    environment:
      - PORT=3000
      - MONGODBURI=mongodb://mongo:27017/vendor-martinez
    ports:
      - "3000:3000"
    depends_on:
      - mongo
      - user-service
      - admin-service
    restart: always

  user-service:
    build:
      context: ./Users
      dockerfile: Dockerfile
    container_name: user-service-martinez
    working_dir: /app
    volumes:
      - ./Users:/app
      - ./_shared:/app/_shared
      - /app/node_modules
    environment:
      - PORT=3001
      - MONGODBURI=mongodb://mongo:27017/user-martinez
    ports:
      - "3001:3001"
    depends_on:
      - mongo
    restart: always

  admin-service:
    build:
      context: ./Admins
      dockerfile: Dockerfile
    container_name: admin-service-martinez
    working_dir: /app
    volumes:
      - ./Admins:/app
      - ./_shared:/app/_shared
      - /app/node_modules
    environment:
      - PORT=3002
      - MONGODBURI=mongodb://mongo:27017/admin-martinez
    ports:
      - "3002:3002"
    depends_on:
      - mongo
    restart: always

  mongo:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    restart: always

volumes:
  mongodb_data:
