name: vendor-service

on:
  push:
    branches:
      - main
  # Uncomment the following lines to enable pull request testing
  # pull_request:
  #   branches: [main]
jobs:
  buildAndTest:
    name: CI Pipeline
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ["18.x"]

    steps:
      # Checkout the repo
      - uses: actions/checkout@v3

      # Set up Node.js ||
      # Initialize Node.js
      - name: Install Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      # Install root dependencies (for monorepo)
      - name: Install dependencies
        run: npm install
        # working-directory: ./Vendors

  deploy:
    name: CD Pipeline
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ["18.x"]
        appname: ["VendorService"]
        application-deploy-name: ["VendorServiceDev"]
        deploy-group: ["VendorService"]
        s3-bucket: ["martinezaicode"]
        s3-filename: ["VendorService-vendorcode-${{ github.sha }}"]
    needs: buildAndTest
    steps:
      # Checkout the repo
      # - name: Checkout code
      - uses: actions/checkout@v3

      # Set up Node.js
      - name: Install Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      # Install root dependencies (for monorepo)
      - name: Install dependencies
        run: npm install
        # working-directory: ./Vendors

  # Add Deployment Here (Optional for prod/staging pipelines)
